### ISSUE TITLE
Syntax Highlighting in VIM Not Consistent With VSCode

### ISSUE THREAD

**Issue by jgcaruso** [tstelzer/new-moon.vim#2]
I've noticed that the syntax highlighting is not consistent with vscode for the same files. Variables are white instead of red for example.

Just curious if I need some specific VIM config or language file in order for it to work better?

thanks!

cc: @tstelzer

**Comment by lchtao26** [comment]
The same as above. the color schema is not as same as vscode.

**Comment by tstelzer** [comment]
Note that vim and vscode have entirely different approaches to syntax highlighting. You can get reasonably close, but you will never have identical color schemes. Even something simple as "variables" are treated very differently.

**Comment by taniarascia** [comment]
Thanks for the clarification, @tstelzer. The vim version of the theme will never be completely in sync with the VSCode version. Feel free to open a PR for any improvements.
